// All item modifications
ItemEvents.modification(event => {

    /*
        Modify item stack sizes
    */
    function increaseStackSize(resource, size) {
        event.modify(resource, item => {item.maxStackSize = size})
    }

    // Increase Chromatic Compound stack size
    increaseStackSize('create:chromatic_compound', 64)
    // Increase all potion stack sizes to 16
    const potion_items= ['minecraft:potion', 'minecraft:splash_potion', 'minecraft:lingering_potion', 'estrogen:gender_change_potion', 'unusualend:warped_potion',
        'irons_spellbooks:oakskin_elixir', 'irons_spellbooks:greater_oakskin_elixir', 'irons_spellbooks:greater_healing_potion', 'irons_spellbooks:invisibility_elixir',
        'irons_spellbooks:greater_invisibility_elixir', 'irons_spellbooks:evasion_elixir', 'irons_spellbooks:greater_evasion_elixir', 'irons_spellbooks:fire_ale',
        'irons_spellbooks:netherward_tincture', 'alexsmobs:lava_bottle']
    potion_items.forEach(element => increaseStackSize(element, 16))
    
    /*
        Modify item rarities
    */
    function uncommon(resource) {
        event.modify(resource, item => {item.rarity = 'UNCOMMON'})
    }
    function rare(resource) {
        event.modify(resource, item => {item.rarity = 'RARE'})
    }
    function epic(resource) {
        event.modify(resource, item => {item.rarity = 'EPIC'})
    }

    const uncommon_items = ['vinery:red_grapejuice', 'vinery:white_grapejuice', 'vinery:red_taiga_grapejuice', 'vinery:white_taiga_grapejuice',
        'vinery:red_jungle_grapejuice', 'vinery:white_jungle_grapejuice', 'vinery:red_savanna_grapejuice', 'vinery:white_savanna_grapejuice', 'vinery:apple_juice',
        'vinery:apple_mash', 'vinery:basket', 'tropicraft:fire_helmet', 'tropicraft:fire_chestplate', 'tropicraft:fire_leggings', 'tropicraft:fire_boots', 'tropicraft:water_wand',
        'tropicraft:exploding_coconut', 'tropicraft:fishing_net', 'tropicraft:drink_mixer', 'tropicraft:air_compressor', 'tropicraft:ashen_mask_horn_monkey',
        'tropicraft:ashen_mask_square_zord', 'tropicraft:ashen_mask_oblongatron', 'tropicraft:ashen_mask_headinator', 'tropicraft:ashen_mask_square_horn',
        'tropicraft:ashen_mask_screw_attack', 'tropicraft:ashen_mask_the_brain', 'tropicraft:ashen_mask_bat_boy', 'tropicraft:ashen_mask_invader', 'tropicraft:ashen_mask_mojo',
        'tropicraft:ashen_mask_warthog', 'tropicraft:ashen_mask_the_heart', 'tropicraft:ashen_mask_enigma', 'tropicraft:azurite_gem', 'tropicraft:eudialyte_gem',
        'tropicraft:zircon_gem', 'tropicraft:azurite_block', 'tropicraft:eudialyte_block', 'tropicraft:zircon_block', 'tropicraft:scale_boots', 'tropicraft:scale_leggings',
        'tropicraft:scale_chestplate', 'tropicraft:scale_helmet', 'tropicraft:blow_gun', 'tropicraft:zircon_hoe', 'tropicraft:eudialyte_hoe', 'tropicraft:zircon_axe',
        'tropicraft:eudialyte_axe', 'tropicraft:zircon_pickaxe', 'tropicraft:eudialyte_pickaxe', 'tropicraft:zircon_shovel', 'tropicraft:eudialyte_shovel', 'tropicraft:zircon_sword',
        'tropicraft:eudialyte_sword', 'tropicraft:black_coffee', 'tropicraft:coconut_water', 'tropicraft:orangeade', 'tropicraft:lemonade', 'tropicraft:cocktail', 'tropicraft:mai_tai',
        'tropicraft:caipirinha', 'tropicraft:pina_colada', 'tropicraft:limeade', 'tropicraft:yellow_scuba_goggles', 'tropicraft:yellow_scuba_flippers', 'tropicraft:yellow_scuba_harness',
        'tropicraft:yellow_pony_bottle', 'tropicraft:pink_scuba_goggles', 'tropicraft:pink_scuba_flippers', 'tropicraft:pink_scuba_harness', 'tropicraft:pink_pony_bottle',
        'unusualend:chorus_helmet', 'unusualend:ender_firefly_egg', 'unusualend:wandering_pearl', 'unusualend:enderling_scrap', 'unusualend:spectral_cloth', 'unusualend:floating_pouch',
        'unusualend:spectral_leggings', 'unusualend:dragling_plush', 'unusualend:bouncy_dagger', 'unusualend:enderblob_shield', 'unusualend:leeching_wand', 'unusualend:citrine_candle',
        'unusualend:citrine_amulet', 'unusualend:pearlescent_upgrade_smithing_template', 'mahoutsukai:powdered_diamond', 'traveloptics:aqua_rune',
        'mahoutsukai:scroll_boundary_displacement', 'mahoutsukai:scroll_boundary_alarm', 'mahoutsukai:scroll_boundary_raise_enclosure', 'mahoutsukai:scroll_boundary_tangible',
        'mahoutsukai:scroll_boundary_gravity', 'mahoutsukai:scroll_boundary_drain_life', 'mahoutsukai:scroll_weapon_shooter', 'mahoutsukai:scroll_projection',
        'mahoutsukai:scroll_reality_marble', 'mahoutsukai:scroll_strengthening', 'mahoutsukai:scroll_treasury_projection', 'mahoutsukai:scroll_proximity_projection',
        'mahoutsukai:scroll_damage_exchange', 'mahoutsukai:scroll_immunity_exchange', 'mahoutsukai:scroll_projectile_displacement', 'mahoutsukai:scroll_protective_displacement',
        'mahoutsukai:scroll_ascension', 'mahoutsukai:scroll_mental_displacement', 'mahoutsukai:scroll_mystic_eyes', 'mahoutsukai:scroll_black_flame', 'mahoutsukai:scroll_prediction',
        'mahoutsukai:scroll_death_collection', 'mahoutsukai:scroll_fay_sight', 'mahoutsukai:scroll_reversion_eyes', 'mahoutsukai:scroll_insight', 'mahoutsukai:scroll_familiars_garden',
        'mahoutsukai:scroll_possess_entity', 'mahoutsukai:scroll_recall_familiar', 'mahoutsukai:scroll_summon_familiar', 'mahoutsukai:scroll_butterfly_effect',
        'mahoutsukai:scroll_swap_familiar', 'mahoutsukai:scroll_spatial_disorientation', 'mahoutsukai:scroll_rho_aias', 'mahoutsukai:scroll_damage_replication',
        'mahoutsukai:scroll_mystic_staff', 'mahoutsukai:scroll_borrowed_authority', 'mahoutsukai:scroll_cup_of_heaven', 'mahoutsukai:scroll_retribution',
        'mahoutsukai:scroll_presence_concealment', 'mahoutsukai:scroll_gandr', 'mahoutsukai:scroll_geas', 'mahoutsukai:scroll_fallen_down', 'mahoutsukai:scroll_probability_alter',
        'mahoutsukai:scroll_selective_displacement', 'mahoutsukai:guidebook', 'aquaculture:box', 'aquaculture:message_in_a_bottle', 'aquaculture:tackle_box', 'aquaculture:worm_farm',
        'aquaculture:diamond_hook', 'aquaculture:light_hook', 'aquaculture:heavy_hook', 'aquaculture:double_hook', 'aquaculture:redstone_hook', 'aquaculture:note_hook',
        'samurai_dynasty:diamond_samurai_helmet', 'samurai_dynasty:diamond_samurai_chestplate', 'samurai_dynasty:diamond_samurai_leggings', 'samurai_dynasty:diamond_samurai_boots',
        'samurai_dynasty:diamond_samurai_helmet_light', 'samurai_dynasty:diamond_samurai_chestplate_light', 'samurai_dynasty:diamond_samurai_leggings_light',
        'samurai_dynasty:diamond_samurai_boots_light', 'samurai_dynasty:diamond_samurai_helmet_master', 'samurai_dynasty:diamond_samurai_chestplate_master',
        'samurai_dynasty:diamond_samurai_leggings_master', 'samurai_dynasty:diamond_samurai_boots_master', 'samurai_dynasty:amethyst_samurai_helmet',
        'samurai_dynasty:amethyst_samurai_chestplate', 'samurai_dynasty:amethyst_samurai_leggings', 'samurai_dynasty:amethyst_samurai_boots', 'samurai_dynasty:quartz_samurai_helmet',
        'samurai_dynasty:quartz_samurai_chestplate', 'samurai_dynasty:quartz_samurai_leggings', 'samurai_dynasty:quartz_samurai_boots', 'samurai_dynasty:red_samurai_helmet',
        'samurai_dynasty:red_samurai_chestplate', 'samurai_dynasty:red_samurai_leggings', 'samurai_dynasty:red_samurai_boots', 'samurai_dynasty:red_samurai_helmet_light',
        'samurai_dynasty:red_samurai_chestplate_light', 'samurai_dynasty:red_samurai_leggings_light', 'samurai_dynasty:red_samurai_boots_light',
        'samurai_dynasty:red_samurai_helmet_master', 'samurai_dynasty:red_samurai_chestplate_master', 'samurai_dynasty:red_samurai_leggings_master',
        'samurai_dynasty:red_samurai_boots_master', 'samurai_dynasty:blue_samurai_helmet', 'samurai_dynasty:blue_samurai_chestplate', 'samurai_dynasty:blue_samurai_leggings',
        'samurai_dynasty:blue_samurai_boots', 'samurai_dynasty:blue_samurai_helmet_light', 'samurai_dynasty:blue_samurai_chestplate_light',
        'samurai_dynasty:blue_samurai_leggings_light', 'samurai_dynasty:blue_samurai_boots_light', 'samurai_dynasty:blue_samurai_helmet_master',
        'samurai_dynasty:blue_samurai_chestplate_master', 'samurai_dynasty:blue_samurai_leggings_master', 'samurai_dynasty:blue_samurai_boots_master',
        'samurai_dynasty:green_samurai_helmet', 'samurai_dynasty:green_samurai_chestplate', 'samurai_dynasty:green_samurai_leggings', 'samurai_dynasty:green_samurai_boots',
        'samurai_dynasty:green_samurai_helmet_light', 'samurai_dynasty:green_samurai_chestplate_light', 'samurai_dynasty:green_samurai_leggings_light',
        'samurai_dynasty:green_samurai_boots_light', 'samurai_dynasty:green_samurai_helmet_master', 'samurai_dynasty:green_samurai_chestplate_master',
        'samurai_dynasty:green_samurai_leggings_master', 'samurai_dynasty:green_samurai_boots_master', 'samurai_dynasty:gray_samurai_helmet',
        'samurai_dynasty:gray_samurai_chestplate', 'samurai_dynasty:gray_samurai_leggings', 'samurai_dynasty:gray_samurai_boots', 'samurai_dynasty:gray_samurai_helmet_light',
        'samurai_dynasty:gray_samurai_chestplate_light', 'samurai_dynasty:gray_samurai_leggings_light', 'samurai_dynasty:gray_samurai_boots_light',
        'samurai_dynasty:gray_samurai_helmet_master', 'samurai_dynasty:gray_samurai_chestplate_master', 'samurai_dynasty:gray_samurai_leggings_master',
        'samurai_dynasty:gray_samurai_boots_master', 'samurai_dynasty:diamond_ninja_helmet', 'samurai_dynasty:diamond_ninja_chestplate', 'samurai_dynasty:diamond_ninja_boots',
        'samurai_dynasty:netherite_ninja_helmet', 'samurai_dynasty:netherite_ninja_chestplate', 'samurai_dynasty:netherite_ninja_boots', 'samurai_dynasty:katana_netherite',
        'samurai_dynasty:wakizashi_netherite', 'samurai_dynasty:naginata_netherite', 'samurai_dynasty:nagamaki_netherite', 'samurai_dynasty:shuko_netherite',
        'samurai_dynasty:tetsubo_netherite', 'samurai_dynasty:odachi_netherite', 'samurai_dynasty:tonbukiri_netherite', 'samurai_dynasty:kamayari_netherite',
        'samurai_dynasty:kunai_netherite', 'samurai_dynasty:kama_netherite', 'samurai_dynasty:sai_netherite', 'samurai_dynasty:spirit_upgrade_smithing_template',
        'supplementaries:cage', 'supplementaries:netherite_trapdoor', 'supplementaries:netherite_door', 'supplementaries:bubble_blower', 'irons_spellbooks:cinder_essence',
        'irons_spellbooks:arcane_salvage', 'irons_spellbooks:dragonskin', 'irons_spellbooks:blank_rune', 'irons_spellbooks:fire_rune',
        'irons_spellbooks:ice_rune', 'irons_spellbooks:lightning_rune', 'irons_spellbooks:ender_rune', 'irons_spellbooks:holy_rune', 'irons_spellbooks:blood_rune',
        'irons_spellbooks:evocation_rune', 'irons_spellbooks:arcane_rune', 'irons_spellbooks:cooldown_rune', 'irons_spellbooks:protection_rune', 'irons_spellbooks:nature_rune',
        'irons_spellbooks:graybeard_staff', 'irons_spellbooks:artificer_cane', 'irons_spellbooks:pyromancer_helmet', 'irons_spellbooks:pyromancer_chestplate',
        'irons_spellbooks:pyromancer_leggings', 'irons_spellbooks:pyromancer_boots', 'irons_spellbooks:electromancer_helmet', 'irons_spellbooks:electromancer_chestplate',
        'irons_spellbooks:electromancer_leggings', 'irons_spellbooks:electromancer_boots', 'irons_spellbooks:archevoker_helmet', 'irons_spellbooks:archevoker_chestplate',
        'irons_spellbooks:archevoker_leggings', 'irons_spellbooks:archevoker_boots', 'irons_spellbooks:cultist_helmet', 'irons_spellbooks:cultist_chestplate',
        'irons_spellbooks:cultist_leggings', 'irons_spellbooks:cultist_boots', 'irons_spellbooks:cryomancer_helmet', 'irons_spellbooks:cryomancer_chestplate',
        'irons_spellbooks:cryomancer_leggings', 'irons_spellbooks:cryomancer_boots', 'irons_spellbooks:shadowwalker_helmet', 'irons_spellbooks:shadowwalker_chestplate',
        'irons_spellbooks:shadowwalker_leggings', 'irons_spellbooks:shadowwalker_boots', 'irons_spellbooks:priest_helmet', 'irons_spellbooks:priest_chestplate',
        'irons_spellbooks:priest_leggings', 'irons_spellbooks:priest_boots', 'irons_spellbooks:plagued_helmet', 'irons_spellbooks:plagued_chestplate',
        'irons_spellbooks:plagued_leggings', 'irons_spellbooks:plagued_boots', 'irons_spellbooks:mana_ring', 'irons_spellbooks:silver_ring', 'irons_spellbooks:cooldown_ring',
        'irons_spellbooks:cast_time_ring', 'irons_spellbooks:heavy_chain_necklace', 'irons_spellbooks:emerald_stoneplate_ring', 'irons_spellbooks:fireward_ring',
        'irons_spellbooks:frostward_ring', 'irons_spellbooks:poisonward_ring', 'irons_spellbooks:conjurers_talisman', 'irons_spellbooks:affinity_ring',
        'irons_spellbooks:concentration_amulet', 'irons_spellbooks:amethyst_resonance_charm', 'aether:golden_amber', 'aether_redux:golden_swet_ball',
        'aether_redux:golden_swet_jelly', 'aether_redux:ring_of_wisdom', 'aether:ice_ring', 'aether:ice_pendant', 'aether_redux:shroom_ring', 'aether:swet_cape',
        'aether_redux:cockatrice_feather', 'aether_redux:infused_veridium_sword', 'aether_redux:infused_veridium_shovel', 'aether_redux:infused_veridium_pickaxe',
        'aether_redux:infused_veridium_axe', 'aether_redux:infused_veridium_hoe', 'aether_redux:veridium_sword', 'aether_redux:veridium_shovel', 'aether_redux:veridium_pickaxe',
        'aether_redux:veridium_axe', 'aether_redux:veridium_hoe', 'aether:candy_cane_sword', 'aether:cold_parachute', 'cataclysm:amethyst_crab_meat',
        'nethers_exoticism:ramboutan_helmet', 'nethers_exoticism:rambutan_shield', 'aether:sun_altar', 'alexscaves:polarity_armor_trim_smithing_template',
        'illagerinvasion:illusionary_dust', 'illagerinvasion:unusual_dust', 'illagerinvasion:platinum_infused_hatchet', 'illagerinvasion:horn_of_sight',
        'forbidden_arcanus:deorum_ingot', 'forbidden_arcanus:deorum_nugget', 'forbidden_arcanus:mundabitur_dust', 'forbidden_arcanus:corrupti_dust', 'forbidden_arcanus:xpetrified_orb',
        'forbidden_arcanus:soul', 'forbidden_arcanus:dragon_scale', 'forbidden_arcanus:golden_feather', 'forbidden_arcanus:ferrognetic_mixture', 'forbidden_arcanus:aureal_bottle',
        'forbidden_arcanus:splash_aureal_bottle', 'forbidden_arcanus:diamond_blacksmith_gavel', 'forbidden_arcanus:darkstone_upgrade_smithing_template',
        'forbidden_arcanus:draco_arcanus_arrow', 'forbidden_arcanus:soul_extractor', 'forbidden_arcanus:slimec_pickaxe', 'forbidden_arcanus:reinforced_deorum_sword',
        'forbidden_arcanus:reinforced_deorum_shovel', 'forbidden_arcanus:reinforced_deorum_pickaxe', 'forbidden_arcanus:reinforced_deorum_axe',
        'forbidden_arcanus:reinforced_deorum_hoe', 'forbidden_arcanus:mystical_dagger', 'forbidden_arcanus:mortem_helmet', 'forbidden_arcanus:mortem_chestplate',
        'forbidden_arcanus:mortem_leggings', 'forbidden_arcanus:mortem_boots', 'forbidden_arcanus:arcane_crystal_obelisk', 'forbidden_arcanus:corrupted_arcane_crystal_obelisk',
        'forbidden_arcanus:deorum_block', 'mahoutsukai:attuned_diamond', 'mahoutsukai:attuned_emerald', 'mahoutsukai:mystic_code', 'mahoutsukai:mystic_code_first_sorcery',
        'mahoutsukai:replica', 'mahoutsukai:proximity_projection_keys', 'mynethersdelight:hoglin_trophy', 'mynethersdelight:waxed_hoglin_trophy', 'mynethersdelight:zoglin_trophy',
        'mynethersdelight:skoglin_trophy', 'mynethersdelight:roast_stuffed_hoglin', 'mutantmonsters:mutant_skeleton_chestplate', 'mutantmonsters:mutant_skeleton_leggings',
        'mutantmonsters:mutant_skeleton_boots', 'immersive_armors:robe_helmet', 'immersive_armors:robe_chestplate', 'immersive_armors:robe_leggings', 'immersive_armors:robe_boots',
        'immersive_armors:wither_helmet', 'immersive_armors:wither_chestplate', 'immersive_armors:wither_leggings', 'immersive_armors:wither_boots',
        'immersive_armors:prismarine_helmet', 'immersive_armors:prismarine_chestplate', 'immersive_armors:prismarine_leggings', 'immersive_armors:prismarine_boots',
        'immersive_armors:divine_helmet', 'immersive_armors:divine_chestplate', 'immersive_armors:divine_leggings', 'immersive_armors:divine_boots',
        'immersive_armors:steampunk_helmet', 'immersive_armors:steampunk_chestplate', 'immersive_armors:steampunk_leggings', 'immersive_armors:steampunk_boots',
        'twilightforest:ice_sword', 'twilightforest:arctic_helmet', 'twilightforest:arctic_chestplate', 'twilightforest:arctic_leggings', 'twilightforest:arctic_boots',
        'twilightforest:ore_magnet', 'twilightforest:knightmetal_helmet', 'twilightforest:knightmetal_chestplate', 'twilightforest:knightmetal_leggings',
        'twilightforest:knightmetal_boots', 'twilightforest:knightmetal_sword', 'twilightforest:knightmetal_pickaxe', 'twilightforest:knightmetal_axe',
        'twilightforest:block_and_chain', 'twilightforest:knightmetal_shield', 'twilightforest:knightmetal_ingot', 'twilightforest:armor_shard_cluster', 'twilightforest:armor_shard',
        'twilightforest:knightmetal_ring', 'twilightforest:magic_map', 'twilightforest:maze_map', 'twilightforest:magic_map_focus', 'twilightforest:maze_map_focus',
        'twilightforest:carminite', 'iceandfire:bestiary', 'iceandfire:dragonegg_red', 'iceandfire:dragonegg_green', 'iceandfire:dragonegg_bronze', 'iceandfire:dragonegg_gray',
        'iceandfire:dragonegg_blue', 'iceandfire:dragonegg_white', 'iceandfire:dragonegg_sapphire', 'iceandfire:dragonegg_silver', 'iceandfire:dragonegg_electric',
        'iceandfire:dragonegg_amythest', 'iceandfire:dragonegg_copper', 'iceandfire:dragonegg_black', 'iceandfire:dragon_skull_fire', 'iceandfire:dragon_skull_ice',
        'iceandfire:dragon_skull_lightning', 'iceandfire:dragonbone_sword_fire', 'iceandfire:dragonbone_sword_ice', 'iceandfire:dragonbone_sword_lightning',
        'iceandfire:dragonarmor_diamond_head', 'iceandfire:dragonarmor_diamond_neck', 'iceandfire:dragonarmor_diamond_body', 'iceandfire:dragonarmor_diamond_tail',
        'iceandfire:dragonarmor_silver_head', 'iceandfire:dragonarmor_silver_neck', 'iceandfire:dragonarmor_silver_body', 'iceandfire:dragonarmor_silver_tail',
        'iceandfire:dragon_stick', 'iceandfire:dragon_horn', 'iceandfire:dragon_flute', 'iceandfire:summoning_crystal_fire', 'iceandfire:summoning_crystal_ice',
        'iceandfire:summoning_crystal_lightning', 'iceandfire:hippogryph_egg', 'iceandfire:diamond_hippogryph_armor', 'iceandfire:armor_red_helmet',
        'iceandfire:armor_red_chestplate', 'iceandfire:armor_red_leggings', 'iceandfire:armor_red_boots', 'iceandfire:armor_bronze_helmet', 'iceandfire:armor_bronze_chestplate',
        'iceandfire:armor_bronze_leggings', 'iceandfire:armor_bronze_boots', 'iceandfire:armor_green_helmet', 'iceandfire:armor_green_chestplate', 'iceandfire:armor_green_leggings',
        'iceandfire:armor_green_boots', 'iceandfire:armor_gray_helmet', 'iceandfire:armor_gray_chestplate', 'iceandfire:armor_gray_leggings', 'iceandfire:armor_gray_boots',
        'iceandfire:armor_blue_helmet', 'iceandfire:armor_blue_chestplate', 'iceandfire:armor_blue_leggings', 'iceandfire:armor_blue_boots', 'iceandfire:armor_white_helmet',
        'iceandfire:armor_white_chestplate', 'iceandfire:armor_white_leggings', 'iceandfire:armor_white_boots', 'iceandfire:armor_sapphire_helmet',
        'iceandfire:armor_sapphire_chestplate', 'iceandfire:armor_sapphire_leggings', 'iceandfire:armor_sapphire_boots', 'iceandfire:armor_silver_helmet',
        'iceandfire:armor_silver_chestplate', 'iceandfire:armor_silver_leggings', 'iceandfire:armor_silver_boots', 'iceandfire:armor_electric_helmet',
        'iceandfire:armor_electric_chestplate', 'iceandfire:armor_electric_leggings', 'iceandfire:armor_electric_boots', 'iceandfire:armor_amythest_helmet',
        'iceandfire:armor_amythest_chestplate', 'iceandfire:armor_amythest_leggings', 'iceandfire:armor_amythest_boots', 'iceandfire:armor_copper_helmet',
        'iceandfire:armor_copper_chestplate', 'iceandfire:armor_copper_leggings', 'iceandfire:armor_copper_boots', 'iceandfire:armor_black_helmet',
        'iceandfire:armor_black_chestplate', 'iceandfire:armor_black_leggings', 'iceandfire:armor_black_boots', 'iceandfire:tide_blue_helmet', 'iceandfire:tide_blue_chestplate',
        'iceandfire:tide_blue_leggings', 'iceandfire:tide_blue_boots', 'iceandfire:tide_bronze_helmet', 'iceandfire:tide_bronze_chestplate', 'iceandfire:tide_bronze_leggings',
        'iceandfire:tide_bronze_boots', 'iceandfire:tide_deepblue_helmet', 'iceandfire:tide_deepblue_chestplate', 'iceandfire:tide_deepblue_leggings',
        'iceandfire:tide_deepblue_boots', 'iceandfire:tide_green_helmet', 'iceandfire:tide_green_chestplate', 'iceandfire:tide_green_leggings', 'iceandfire:tide_green_boots',
        'iceandfire:tide_purple_helmet', 'iceandfire:tide_purple_chestplate', 'iceandfire:tide_purple_leggings', 'iceandfire:tide_purple_boots', 'iceandfire:tide_red_helmet',
        'iceandfire:tide_red_chestplate', 'iceandfire:tide_red_leggings', 'iceandfire:tide_red_boots', 'iceandfire:tide_teal_helmet', 'iceandfire:tide_teal_chestplate',
        'iceandfire:tide_teal_leggings', 'iceandfire:tide_teal_boots', 'iceandfire:hippogryph_skull', 'iceandfire:cyclops_skull', 'iceandfire:cockatrice_skull',
        'iceandfire:stymphalian_skull', 'iceandfire:troll_skull', 'iceandfire:amphithere_skull', 'iceandfire:seaserpent_skull', 'iceandfire:hydra_skull', 'ars_elemental:fire_hat',
        'ars_elemental:fire_robes', 'ars_elemental:fire_leggings', 'ars_elemental:fire_boots', 'ars_elemental:air_hat', 'ars_elemental:air_robes', 'ars_elemental:air_leggings',
        'ars_elemental:air_boots', 'ars_elemental:earth_hat', 'ars_elemental:earth_robes', 'ars_elemental:earth_leggings', 'ars_elemental:earth_boots', 'ars_elemental:aqua_hat',
        'ars_elemental:aqua_robes', 'ars_elemental:aqua_leggings', 'ars_elemental:aqua_boots', 'ars_elemental:anima_essence', 'ars_elemental:fire_caster_tome',
        'ars_elemental:water_caster_tome', 'ars_elemental:air_caster_tome', 'ars_elemental:earth_caster_tome', 'ars_elemental:anima_caster_tome',
        'ars_elemental:manipulation_caster_tome', 'ribbits:maraca', 'ars_nouveau:novice_spell_book', 'ars_nouveau:ring_of_lesser_discount', 'ars_nouveau:ring_of_greater_discount',
        'ars_elemental:siren_shards', 'ars_nouveau:starbuncle_shards', 'ars_nouveau:whirlisprig_shards', 'ars_nouveau:dominion_wand', 'ars_nouveau:amulet_of_mana_boost',
        'ars_nouveau:amulet_of_mana_regen', 'ars_nouveau:wixie_shards', 'ars_nouveau:amplify_arrow', 'ars_nouveau:split_arrow', 'ars_nouveau:pierce_arrow',
        'ars_nouveau:experience_gem', 'ars_nouveau:greater_experience_gem', 'ars_nouveau:caster_tome', 'ars_nouveau:drygmy_shard', 'ars_nouveau:dowsing_rod',
        'ars_nouveau:abjuration_essence', 'ars_nouveau:conjuration_essence', 'ars_nouveau:air_essence', 'ars_nouveau:earth_essence', 'ars_nouveau:fire_essence',
        'ars_nouveau:manipulation_essence', 'ars_nouveau:water_essence', 'ars_nouveau:arcanist_boots', 'ars_nouveau:arcanist_leggings', 'ars_nouveau:arcanist_robes',
        'ars_nouveau:arcanist_hood', 'ars_nouveau:sorcerer_boots', 'ars_nouveau:sorcerer_leggings', 'ars_nouveau:sorcerer_robes', 'ars_nouveau:sorcerer_hood',
        'ars_nouveau:battlemage_boots', 'ars_nouveau:battlemage_leggings', 'ars_nouveau:battlemage_robes', 'ars_nouveau:battlemage_hood', 'ars_nouveau:splash_flask_cannon',
        'ars_nouveau:lingering_flask_cannon', 'ars_nouveau:warp_scroll', 'ars_nouveau:storage_lectern', 'ars_nouveau:basic_spell_turret', 'ars_nouveau:timer_spell_turret',
        'ars_nouveau:rotating_spell_turret', 'ars_nouveau:spell_turret', 'ends_delight:purpur_knife', 'ends_delight:dragon_leg_with_sauce_block', 'domesticationinnovation:drum',
        'domesticationinnovation:wayward_lantern', 'domesticationinnovation:deed_of_ownership', 'experienceobelisk:cognitive_crystal', 'experienceobelisk:cognitive_crystal_block',
        'experienceobelisk:experience_jelly', 'experienceobelisk:bibliophage', 'experienceobelisk:cognitive_flux', 'galosphere:silver_upgrade_smithing_template',
        'galosphere:preserved_template', 'galosphere:saltbound_tablet', 'galosphere:preserved_flesh', 'justhammers:diamond_hammer', 'justhammers:diamond_impact_hammer',
        'justhammers:diamond_reinforced_hammer', 'justhammers:diamond_reinforced_impact_hammer', 'justhammers:diamond_destructor_hammer', 'justhammers:impact_core',
        'justhammers:reinforced_core', 'patchouli:guide_book', 'dimdungeons:block_gilded_portal', 'dimdungeons:block_portal_keyhole', 'dimdungeons:item_secret_bell',
        'dimdungeons:item_homeward_pearl', 'dimdungeons:item_portal_key', 'dimdungeons:block_portal_crown', 'cataclysm:ignitium_upgrade_smithing_template',
        'cataclysm:cursium_upgrade_smithing_template', 'cataclysm:bone_reptile_helmet', 'cataclysm:bone_reptile_chestplate', 'call_of_yucutan:hematite',
        'call_of_yucutan:ancient_gold_ingot', 'call_of_yucutan:mayan_calendar', 'call_of_yucutan:ancient_gold', 'call_of_yucutan:hematite_shield', 'call_of_yucutan:hematite_block',
        'call_of_yucutan:obsidian_tecpatl', 'call_of_yucutan:obsidian_spear', 'iceandfire:dragonforge_fire_core', 'iceandfire:dragonforge_ice_core',
        'iceandfire:dragonforge_lightning_core', 'iceandfire:dragonforge_fire_core_disabled', 'iceandfire:dragonforge_ice_core_disabled',
        'iceandfire:dragonforge_lightning_core_disabled', 'create:potato_cannon', 'create:copper_backtank', 'create:blaze_burner', 'create:electron_tube',
        'create:precision_mechanism', 'create:blaze_cake', 'create:sturdy_sheet', 'create:goggles', 'create:copper_diving_helmet', 'create:copper_diving_boots',
        'arsdelight:wilden_salad', 'arsdelight:honey_glazed_chimera', 'alexsmobs:maraca', 'alexsmobs:sombrero', 'alexsmobs:animal_dictionary', 'alexsmobs:blood_sprayer',
        'alexsmobs:straddlite', 'alexsmobs:pupfish_locator', 'alexsmobs:rocky_chestplate', 'alexsmobs:froststalker_helmet', 'alexsmobs:skelewag_sword', 'alexsmobs:unsettling_kimono',
        'aetherdelight:veridium_knife', 'aetherdelight:zanite_knife', 'minecraft:diamond', 'minecraft:netherite_scrap', 'minecraft:ender_pearl', 'minecraft:ender_eye',
        'minecraft:blaze_rod', 'quark:dragon_scale', 'minecraft:shulker_shell', 'minecraft:phantom_membrane', 'minecraft:turtle_helmet',
        'minecraft:netherite_upgrade_smithing_template', 'minecraft:sentry_armor_trim_smithing_template', 'minecraft:vex_armor_trim_smithing_template',
        'minecraft:wild_armor_trim_smithing_template', 'minecraft:coast_armor_trim_smithing_template', 'minecraft:dune_armor_trim_smithing_template',
        'minecraft:wayfinder_armor_trim_smithing_template', 'minecraft:raiser_armor_trim_smithing_template', 'minecraft:shaper_armor_trim_smithing_template',
        'minecraft:host_armor_trim_smithing_template', 'minecraft:ward_armor_trim_smithing_template', 'minecraft:silence_armor_trim_smithing_template',
        'minecraft:tide_armor_trim_smithing_template', 'minecraft:snout_armor_trim_smithing_template', 'minecraft:rib_armor_trim_smithing_template',
        'minecraft:eye_armor_trim_smithing_template', 'minecraft:spire_armor_trim_smithing_template', 'quark:smithing_template_rune', 'minecraft:diamond_sword',
        'minecraft:diamond_axe', 'minecraft:diamond_helmet', 'minecraft:diamond_chestplate', 'minecraft:diamond_leggings', 'minecraft:diamond_boots',
        'savage_and_ravage:griefer_helmet', 'savage_and_ravage:griefer_chestplate', 'savage_and_ravage:griefer_leggings', 'savage_and_ravage:griefer_boots',
        'savage_and_ravage:blast_proof_plating', 'endergetic:booflo_vest', 'minecraft:diamond_horse_armor', 'aether:diamond_gloves', 'minecraft:spectral_arrow',
        'savage_and_ravage:mischief_arrow', 'minecraft:tipped_arrow', 'quark:torch_arrow', 'minecraft:diamond_shovel', 'minecraft:diamond_pickaxe', 'minecraft:diamond_axe',
        'minecraft:diamond_hoe', 'quark:pickarang', 'minecraft:spyglass', 'quark:pathfinders_quill', 'constructionwand:diamond_wand', 'minecraft:saddle', 'quark:backpack',
        'quark:forgotten_hat', 'map_atlases:atlas', 'solcarrot:food_book', 'the_bumblezone:buzzing_briefcase', 'breezy:hot_air_balloon', 'minecraft:diamond_block',
        'savage_and_ravage:blast_proof_plates', 'savage_and_ravage:blast_proof_stairs', 'savage_and_ravage:blast_proof_slab', 'minecraft:ender_chest', 'minecraft:respawn_anchor',
        'traveloptics:witherite_upgrade_smithing_template', 'traveloptics:tectonic_upgrade_smithing_template', 'traveloptics:abyssal_upgrade_smithing_template',
        'iceandfire:hydra_arrow', 'iceandfire:amphithere_arrow', 'iceandfire:sea_serpent_arrow', 'iceandfire:deathworm_egg', 'iceandfire:deathworm_egg_giant',
        'galosphere:sterling_horse_armor', 'call_of_yucutan:obsidian_arrow', 'aether_redux:veridium_block', 'experienceobelisk:nutrient_agar', 'experienceobelisk:whisperglass',
        'apotheosis:library', 'apotheosis:infused_hellshelf', 'apotheosis:blazing_hellshelf', 'apotheosis:glowing_hellshelf', 'apotheosis:deepshelf', 'apotheosis:echoing_deepshelf',
        'apotheosis:soul_touched_deepshelf', 'apotheosis:infused_seashelf', 'apotheosis:crystal_seashelf', 'apotheosis:heart_seashelf', 'apotheosis:endshelf', 'apotheosis:rectifier_t3',
        'apotheosis:rectifier_t2', 'apotheosis:rectifier', 'apotheosis:inert_trident', 'apotheosis:prismatic_web', 'apotheosis:ender_lead', 'hexcasting:quenched_allay',
        'hexcasting:quenched_allay_tiles', 'hexcasting:quenched_allay_bricks', 'hexcasting:quenched_allay_bricks_small', 'hexcasting:quenched_allay_shard',
        'hexcasting:impetus/rightclick', 'hexcasting:impetus/look', 'hexcasting:impetus/redstone', 'hexcasting:directrix/redstone', 'hexcasting:directrix/boolean',
        'hexcasting:akashic_record', 'minecraft:budding_amethyst', 'hexcasting:charged_amethyst', 'hexcasting:staff/oak', 'hexcasting:staff/spruce', 'hexcasting:staff/birch',
        'hexcasting:staff/jungle', 'hexcasting:staff/acacia', 'hexcasting:staff/dark_oak', 'hexcasting:staff/crimson', 'hexcasting:staff/warped', 'hexcasting:staff/mangrove',
        'hexcasting:staff/cherry', 'hexcasting:staff/bamboo', 'hexcasting:lens', 'hexcasting:battery', 'hexcasting:dye_colorizer_white', 'hexcasting:dye_colorizer_orange',
        'hexcasting:dye_colorizer_magenta', 'hexcasting:dye_colorizer_light_blue', 'hexcasting:dye_colorizer_yellow', 'hexcasting:dye_colorizer_lime', 'hexcasting:dye_colorizer_pink',
        'hexcasting:dye_colorizer_gray', 'hexcasting:dye_colorizer_light_gray', 'hexcasting:dye_colorizer_cyan', 'hexcasting:dye_colorizer_purple', 'hexcasting:dye_colorizer_blue',
        'hexcasting:dye_colorizer_brown', 'hexcasting:dye_colorizer_green', 'hexcasting:dye_colorizer_red', 'hexcasting:dye_colorizer_black', 'hexcasting:default_colorizer',
        'ancient_aether:valkyrum_ring', 'ancient_aether:hermes_ring', 'ancient_aether:valkyrum_pendant', 'ancient_aether:hermes_pendant', 'ancient_aether:valkyrum_helmet',
        'ancient_aether:valkyrum_chestplate', 'ancient_aether:valkyrum_leggings', 'ancient_aether:valkyrum_boots', 'ancient_aether:valkyrum_gloves', 'aether:shield_of_repulsion',
        'ancient_aether:valkyrum_sword', 'ancient_aether:valkyrum_lance', 'ancient_aether:valkyrum_shovel', 'ancient_aether:valkyrum_pickaxe', 'ancient_aether:valkyrum_axe',
        'ancient_aether:valkyrum_hoe', 'aether:hammer_of_kingbdogz', 'aether:cloud_staff', 'aether:white_moa_egg', 'ancient_aether:turquoise_moa_egg', 'ancient_aether:teal_moa_egg',
        'ancient_aether:sky_blue_moa_egg', 'aether:blue_moa_egg', 'ancient_aether:lavender_moa_egg', 'ancient_aether:sakura_moa_egg', 'ancient_aether:violet_moa_egg',
        'ancient_aether:burgundy_moa_egg', 'aether:black_moa_egg', 'ancient_aether:valkyrum', 'aether_redux:raw_valkyrum', 'aether_redux:refined_sentrite', 'aether_redux:sentrite_chunk',
        'aether_redux:sentry_chip', 'aquaculture:diamond_fillet_knife', 'aquaculture:diamond_fishing_rod', 'traveloptics:darkness_upgrade_smithing_template',
        'aether_redux:refined_sentrite_block', 'ancient_aether:valkyrum_block', 'iceandfire:fire_lily', 'iceandfire:frost_lily', 'iceandfire:lightning_lily', 'iceandfire:lectern',
        'farmersdelight:diamond_knife', 'apotheosis:diamond_mining_arrow', 'aether:phoenix_gloves', 'aether:phoenix_helmet', 'aether:phoenix_chestplate', 'aether:phoenix_leggings',
        'aether:phoenix_boots', 'aether:neptune_helmet', 'aether:neptune_chestplate', 'aether:neptune_leggings', 'aether:neptune_boots', 'aether:neptune_gloves',
        'wan_ancient_beasts:spike_armor_trim_smithing_template', 'wan_ancient_beasts:sniff_armor_trim_smithing_template', 'wan_ancient_beasts:sniffer_skull', 'wan_ancient_beasts:eater_skull',
        'wan_ancient_beasts:walker_skull', 'wan_ancient_beasts:crusher_skull', 'wan_ancient_beasts:glider_skull', 'wan_ancient_beasts:soarer_skull',
        'wan_ancient_beasts:hang_glider', 'wan_ancient_beasts:white_hang_glider', 'wan_ancient_beasts:light_gray_hang_glider', 'wan_ancient_beasts:gray_hang_glider',
        'wan_ancient_beasts:black_hang_glider', 'wan_ancient_beasts:brown_hang_glider', 'wan_ancient_beasts:red_hang_glider', 'wan_ancient_beasts:orange_hang_glider',
        'wan_ancient_beasts:yellow_hang_glider', 'wan_ancient_beasts:lime_hang_glider', 'wan_ancient_beasts:green_hang_glider', 'wan_ancient_beasts:light_blue_hang_glider',
        'wan_ancient_beasts:cyan_hang_glider', 'wan_ancient_beasts:blue_hang_glider', 'wan_ancient_beasts:purple_hang_glider', 'wan_ancient_beasts:magenta_hang_glider',
        'wan_ancient_beasts:pink_hang_glider', 'wan_ancient_beasts:ancient_club', 'wan_ancient_beasts:reinforced_shield', 'experienceobelisk:transforming_focus',
        'psi:cad_assembly_iron', 'psi:cad_assembly_gold', 'psi:cad_battery_extended', 'psi:exosuit_controller', 'psi:cad_core_overclocked', 'psi:cad_core_conductive',
        'psi:cad_socket_signaling', 'psi:cad_socket_large', 'psi:ebony_substance', 'psi:ivory_substance', 'ars_elemental:base_bangle', 'wan_ancient_beasts:surfer_skull',
        'wan_ancient_beasts:surfer_armor'
    ]
    uncommon_items.forEach(element => uncommon(element))
        
    const rare_items = ['vinery:mead', 'vinery:apple_cider', 'vinery:apple_wine', 'create:shadow_steel', 'create:refined_radiance', 'create:shadow_steel_casing', 'create:refined_radiance_casing',
        'vinery:mellohi_wine', 'vinery:glowing_wine', 'vinery:solaris_wine', 'vinery:noir_wine', 'vinery:red_wine', 'vinery:strad_wine', 'vinery:cherry_wine', 'vinery:cristel_wine',
        'vinery:creepers_crush', 'vinery:kelp_cider', 'vinery:lilitu_wine', 'vinery:jo_special_mixture', 'vinery:eiswein', 'vinery:aegis_wine', 'vinery:bolvar_wine',
        'vinery:chorus_wine', 'vinery:villagers_fright', 'vinery:clark_wine', 'vinery:magnetic_wine', 'vinery:stal_wine', 'vinery:chenet_wine', 'tropicraft:white_pearl',
        'tropicraft:black_pearl', 'tropicraft:zirconium_gem', 'tropicraft:shaka_ingot', 'tropicraft:manganese_ingot', 'tropicraft:zirconium_block', 'tropicraft:shaka_block',
        'tropicraft:manganese_block', 'tropicraft:zirconium_hoe', 'tropicraft:zirconium_axe', 'tropicraft:zirconium_pickaxe', 'tropicraft:zirconium_shovel', 'tropicraft:zirconium_sword',
        'unusualend:wandering_stew', 'unusualend:void_totem', 'unusualend:spirit_smile_helmet', 'unusualend:spirit_malice_helmet', 'unusualend:spirit_grim_helmet',
        'unusualend:spirit_mania_helmet', 'unusualend:spirit_vice_helmet', 'unusualend:spirit_twist_helmet', 'unusualend:pearlescent_ring', 'unusualend:pearlescent_ingot',
        'unusualend:pearlescent_block', 'unusualend:pearlescent_upgrade_smithing_template', 'unusualend:ancient_armor_trim_smithing_template', 'unusualend:pearlescent_sword',
        'unusualend:pearlescent_pickaxe', 'unusualend:pearlescent_axe', 'unusualend:pearlescent_shovel', 'unusualend:pearlescent_hoe', 'unusualend:warped_chestplate',
        'unusualend:warped_boots', 'unusualend:warped_spear', 'unusualend:scale_horse_armor', 'unusualend:warped_anchor', 'unusualend:prismatic_mirror',
        'aquaculture:lockbox', 'aquaculture:neptunium_block', 'aquaculture:neptunium_ingot', 'aquaculture:neptunium_nugget', 'architects_palette:netherite_nub',
        'aquaculture:nether_star_hook', 'kubejs:depths_portal', 'kubejs:dragon_portal', 'kubejs:inbetween_portal', 'supplementaries:safe', 'galosphere:cured_membrane_block',
        'irons_spellbooks:oakskin_elixir', 'irons_spellbooks:greater_oakskin_elixir', 'irons_spellbooks:greater_healing_potion', 'irons_spellbooks:invisibility_elixir',
        'irons_spellbooks:greater_invisibility_elixir', 'irons_spellbooks:evasion_elixir', 'irons_spellbooks:greater_evasion_elixir', 'irons_spellbooks:fire_ale',
        'irons_spellbooks:netherward_tincture', 'irons_spellbooks:blood_staff', 'irons_spellbooks:netherite_mage_helmet', 'kubejs:enchant_catalyst',
        'irons_spellbooks:netherite_mage_chestplate', 'irons_spellbooks:netherite_mage_leggings', 'irons_spellbooks:netherite_mage_boots', 'aether_redux:enchanted_blueberry_pie',
        'aether:gravitite_helmet', 'aether:gravitite_chestplate', 'aether:gravitite_leggings', 'aether:gravitite_boots', 'aether:gravitite_gloves', 'aether_redux:sentry_ring',
        'aether_redux:ring_of_construction', 'aether_redux:feather_of_warding', 'aether_redux:snailshell_shield', 'aether:gravitite_sword', 'aether:gravitite_shovel',
        'aether:gravitite_pickaxe', 'aether:gravitite_axe', 'aether:gravitite_hoe', 'aether:treasure_chest', 'forbidden_arcanus:corrupt_soul',
        'forbidden_arcanus:silver_dragon_scale', 'forbidden_arcanus:golden_dragon_scale', 'forbidden_arcanus:aquatic_dragon_scale', 'forbidden_arcanus:spawner_scrap',
        'forbidden_arcanus:quantum_catcher', 'forbidden_arcanus:shiny_zombie_arm', 'forbidden_arcanus:stellarite_piece', 'forbidden_arcanus:netherite_blacksmith_gavel',
        'forbidden_arcanus:reinforced_deorum_blacksmith_gavel', 'forbidden_arcanus:terrastomp_prism', 'forbidden_arcanus:sea_prism', 'forbidden_arcanus:whirlwind_prism',
        'forbidden_arcanus:smelter_prism', 'forbidden_arcanus:draco_arcanus_staff', 'forbidden_arcanus:draco_arcanus_sword', 'forbidden_arcanus:draco_arcanus_shovel',
        'forbidden_arcanus:draco_arcanus_pickaxe', 'forbidden_arcanus:draco_arcanus_axe', 'forbidden_arcanus:draco_arcanus_hoe', 'forbidden_arcanus:draco_arcanus_scepter',
        'forbidden_arcanus:draco_arcanus_helmet', 'forbidden_arcanus:draco_arcanus_chestplate', 'forbidden_arcanus:draco_arcanus_leggings', 'forbidden_arcanus:draco_arcanus_boots',
        'forbidden_arcanus:dark_nether_star_block', 'forbidden_arcanus:stellarite_block', 'mahoutsukai:clarent', 'mahoutsukai:weapon_projectile_bow', 'mahoutsukai:rule_breaker',
        'mahoutsukai:mystic_staff', 'mahoutsukai:spatial_disorientation_staff', 'twilightforest:ore_map', 'twilightforest:transformation_powder', 'iceandfire:fire_dragon_heart',
        'iceandfire:ice_dragon_heart', 'iceandfire:lightning_dragon_heart', 'iceandfire:hippogryph_talon', 'iceandfire:pixie_wings', 'iceandfire:siren_tear',
        'iceandfire:hippocampus_fin', 'iceandfire:cockatrice_eye', 'iceandfire:tide_trident_inventory', 'iceandfire:tide_trident', 'iceandfire:deathworm_tounge',
        'iceandfire:dread_queen_staff', 'iceandfire:dread_queen_sword', 'iceandfire:lich_staff', 'iceandfire:ghost_ingot', 'ars_elemental:everfull_urn',
        'ars_elemental:siren_charm', 'ars_elemental:firenando_charm', 'ars_nouveau:bookwyrm_charm', 'ars_nouveau:starbuncle_charm', 'ars_nouveau:apprentice_spell_book',
        'ars_nouveau:whirlisprig_charm', 'ars_nouveau:wixie_charm', 'ars_nouveau:void_jar', 'ars_nouveau:drygmy_charm', 'ars_nouveau:amethyst_golem_charm',
        'ars_nouveau:stable_warp_scroll', 'estrogen:estrogen_pill_block', 'ends_delight:dragon_egg_shell_knife', 'ends_delight:dragon_tooth_knife',
        'experienceobelisk:cognitive_sword', 'experienceobelisk:cognitive_shovel', 'experienceobelisk:cognitive_pickaxe', 'experienceobelisk:cognitive_axe',
        'experienceobelisk:cognitive_hoe', 'experienceobelisk:attunement_staff', 'experienceobelisk:enlightened_amulet', 'experienceobelisk:cognitive_amalgam',
        'experienceobelisk:cognitive_alloy', 'experienceobelisk:astute_assembly', 'experienceobelisk:experience_fountain', 'experienceobelisk:precision_dispeller',
        'experienceobelisk:molecular_metamorpher', 'experienceobelisk:nightmare_bottle', 'experienceobelisk:daydream_bottle', 'galosphere:cured_membrane',
        'travelerscompass:travelerscompass', 'transmog:transmogrification_table', 'justhammers:netherite_hammer', 'justhammers:netherite_impact_hammer',
        'justhammers:netherite_reinforced_hammer', 'justhammers:netherite_reinforced_impact_hammer', 'justhammers:netherite_destructor_hammer', 'justhammers:reinforced_impact_core',
        'dimdungeons:item_blank_advanced_key', 'dimdungeons:item_blank_build_key', 'call_of_yucutan:fragment_of_death', 'call_of_yucutan:fragment_of_rebirth',
        'call_of_yucutan:music_disc_xibalba', 'call_of_yucutan:music_disc_awakening', 'create:netherite_backtank', 'create:netherite_diving_helmet', 'create:netherite_diving_boots',
        'alexsmobs:soul_heart', 'alexsmobs:mimicream', 'alexsmobs:straddleboard', 'alexsmobs:hemolymph_blaster', 'alexsmobs:pigshoes', 'alexsmobs:straddle_helmet',
        'alexsmobs:straddle_saddle', 'alexsmobs:skreecher_soul', 'alexsmobs:novelty_hat', 'alexsmobs:sculk_boomer', 'aetherdelight:enchanted_pie_slice',
        'aetherdelight:gravitite_knife', 'minecraft:echo_shard', 'minecraft:nether_star', 'minecraft:heart_of_the_sea', 'minecraft:netherite_ingot', 'minecraft:disc_fragment_5',
        'dreadsteel:kit_default', 'dreadsteel:kit_white', 'dreadsteel:kit_black', 'dreadsteel:kit_bronze', 'minecraft:netherite_sword', 'minecraft:netherite_axe',
        'minecraft:netherite_helmet', 'minecraft:netherite_chestplate', 'minecraft:netherite_leggings', 'minecraft:netherite_boots', 'aether:netherite_gloves',
        'minecraft:netherite_shovel', 'minecraft:netherite_pickaxe', 'minecraft:netherite_axe', 'minecraft:netherite_hoe', 'quark:flamerang', 'minecraft:recovery_compass',
        'constructionwand:infinity_wand', 'minecraft:netherite_block', 'minecraft:dragon_head', 'samurai_dynasty:netherite_samurai_helmet',
        'samurai_dynasty:netherite_samurai_chestplate', 'samurai_dynasty:netherite_samurai_leggings', 'samurai_dynasty:netherite_samurai_boots',
        'samurai_dynasty:netherite_samurai_helmet_light', 'samurai_dynasty:netherite_samurai_chestplate_light', 'samurai_dynasty:netherite_samurai_leggings_light',
        'samurai_dynasty:netherite_samurai_boots_light', 'samurai_dynasty:netherite_samurai_helmet_master', 'samurai_dynasty:netherite_samurai_chestplate_master',
        'samurai_dynasty:netherite_samurai_leggings_master', 'samurai_dynasty:netherite_samurai_boots_master', 'samurai_dynasty:brass_samurai_helmet',
        'samurai_dynasty:brass_samurai_chestplate', 'samurai_dynasty:brass_samurai_leggings', 'samurai_dynasty:brass_samurai_boots', 'samurai_dynasty:draco_samurai_helmet',
        'samurai_dynasty:draco_samurai_chestplate', 'samurai_dynasty:draco_samurai_leggings', 'samurai_dynasty:draco_samurai_boots', 'iceandfire:fire_dragon_blood',
        'iceandfire:ice_dragon_blood', 'iceandfire:lightning_dragon_blood', 'experienceobelisk:insightful_agar', 'experienceobelisk:calcarine_matrix',
        'experienceobelisk:cognitive_shears', 'experienceobelisk:cognitive_rod', 'experienceobelisk:cognitive_alloy_block', 'experienceobelisk:cognitive_helmet',
        'experienceobelisk:cognitive_chestplate', 'experienceobelisk:cognitive_leggings', 'experienceobelisk:cognitive_boots', 'apotheosis:filtering_shelf',
        'apotheosis:pearl_endshelf', 'apotheosis:draconic_endshelf', 'apotheosis:echoing_sculkshelf', 'apotheosis:soul_touched_sculkshelf', 'apotheosis:warden_tendril',
        'experienceobelisk:mending_neurogel', 'hexcasting:staff/edified', 'hexcasting:staff/quenched', 'hexcasting:staff/mindsplice', 'hexcasting:pride_colorizer_agender',
        'hexcasting:pride_colorizer_aroace', 'hexcasting:pride_colorizer_aromantic', 'hexcasting:pride_colorizer_asexual', 'hexcasting:pride_colorizer_bisexual',
        'hexcasting:pride_colorizer_demiboy', 'hexcasting:pride_colorizer_demigirl', 'hexcasting:pride_colorizer_gay', 'hexcasting:pride_colorizer_genderfluid',
        'hexcasting:pride_colorizer_genderqueer', 'hexcasting:pride_colorizer_intersex', 'hexcasting:pride_colorizer_lesbian', 'hexcasting:pride_colorizer_nonbinary',
        'hexcasting:pride_colorizer_pansexual', 'hexcasting:pride_colorizer_plural', 'hexcasting:pride_colorizer_transgender', 'hexcasting:uuid_colorizer', 'aether:sentry_boots',
        'ancient_aether:warrior_ring', 'ancient_aether:warrior_pendant', 'ancient_aether:growth_ring', 'ancient_aether:growth_pendant', 'ancient_aether:ancient_ring',
        'ancient_aether:ancient_pendant', 'ancient_aether:shield_of_inebriation', 'ancient_aether:shield_of_remediation', 'aether:valkyrie_cape', 'aether:iron_bubble',
        'aether:flaming_sword', 'aether:holy_sword', 'aether:lightning_sword', 'aether:phoenix_bow', 'ancient_aether:ancient_sword', 'ancient_aether:wynd_armor_trim_smithing_template',
        'ancient_aether:whale_armor_trim_smithing_template', 'ancient_aether:ascended_armor_trim_smithing_template', 'traveloptics:music_disc_169', 'farmersdelight:netherite_knife',
        'experienceobelisk:cognitive_bow', 'experienceobelisk:flint_and_cognitive_alloy', 'experienceobelisk:mending_neurogel_blob', 'cataclysm:lacrima', 'cataclysm:azure_sea_shield',
        'psi:cad_assembly_psimetal', 'psi:cad_assembly_ivory_psimetal', 'psi:cad_assembly_ebony_psimetal', 'psi:psimetal_exosuit_helmet', 'psi:psimetal_exosuit_chestplate',
        'psi:psimetal_exosuit_leggings', 'psi:psimetal_exosuit_boots', 'psi:cad_battery_ultradense', 'psi:cad_core_hyperclocked', 'psi:cad_core_radiative', 'psi:cad_socket_transmissive',
        'psi:cad_socket_huge', 'psi:psidust', 'psi:psidust_block', 'psi:psigem', 'psi:psigem_block', 'psi:psimetal', 'psi:psimetal_block', 'psi:ebony_psimetal',
        'psi:ebony_psimetal_block', 'psi:ivory_psimetal', 'psi:ivory_psimetal_block', 'psi:white_psimetal_plate', 'psi:lit_white_psimetal_plate',
        'psi:black_psimetal_plate', 'psi:lit_black_psimetal_plate', 'psi:vector_ruler', 'psi:psimetal_sword', 'psi:psimetal_shovel', 'psi:psimetal_pickaxe',
        'psi:psimetal_axe'
    ]
    rare_items.forEach(element => rare(element))

    const epic_items = ['vinery:winemaker_leggings', 'vinery:winemaker_boots', 'kubejs:hyper_enchant_catalyst', 'kubejs:obfuscated', 'create:chromatic_compound',
        'vinery:jellie_wine', 'vinery:bottle_mojang_noir', 'tarotcards:tarot_deck', 'tarotcards:death', 'tarotcards:judgement', 'tarotcards:justice', 'tarotcards:strength',
        'tarotcards:temperance', 'tarotcards:the_chariot', 'tarotcards:the_devil', 'tarotcards:the_emperor', 'tarotcards:the_empress', 'tarotcards:the_fool', 'tarotcards:the_hanged_man',
        'tarotcards:the_hermit', 'tarotcards:the_hierophant', 'tarotcards:the_high_priestess', 'tarotcards:the_lovers', 'tarotcards:the_magician', 'tarotcards:the_moon',
        'tarotcards:the_star', 'tarotcards:the_sun', 'tarotcards:the_tower', 'tarotcards:the_world', 'tarotcards:wheel_of_fortune', 'trofers:small_pillar', 'trofers:medium_pillar',
        'trofers:large_pillar', 'trofers:small_plate', 'trofers:medium_plate', 'trofers:large_plate', 'endrem:black_eye', 'endrem:cold_eye', 'endrem:corrupted_eye', 'endrem:lost_eye',
        'endrem:nether_eye', 'endrem:old_eye', 'endrem:rogue_eye', 'endrem:cursed_eye', 'endrem:evil_eye', 'endrem:guardian_eye', 'endrem:magical_eye', 'endrem:witch_eye',
        'endrem:exotic_eye', 'aquaculture:neptunes_bounty', 'aquaculture:neptunium_axe', 'aquaculture:neptunium_boots', 'aquaculture:neptunium_bow', 'aquaculture:neptunium_chestplate',
        'aquaculture:neptunium_fillet_knife', 'aquaculture:neptunium_fishing_rod', 'aquaculture:neptunium_helmet', 'aquaculture:neptunium_hoe', 'aquaculturedelight:neptunium_knife',
        'aquaculture:neptunium_leggings', 'aquaculture:neptunium_pickaxe', 'aquaculture:neptunium_shovel', 'aquaculture:neptunium_sword', 'aquaculture:treasure_chest',
        'supplementaries:antique_ink', 'samurai_dynasty:mage_samurai_boots', 'aether:golden_parachute', 'forbidden_arcanus:eternal_stella', 'forbidden_arcanus:enchanted_soul',
        'forbidden_arcanus:artisan_relic', 'forbidden_arcanus:crescent_moon', 'forbidden_arcanus:crimson_stone', 'forbidden_arcanus:soul_crimson_stone',
        'forbidden_arcanus:elementarium', 'forbidden_arcanus:divine_pact', 'forbidden_arcanus:maledictus_pact', 'forbidden_arcanus:tyr_helmet', 'forbidden_arcanus:tyr_chestplate',
        'forbidden_arcanus:tyr_leggings', 'forbidden_arcanus:tyr_boots', 'forbidden_arcanus:arcane_dragon_egg', 'mahoutsukai:morgan', 'mahoutsukai:caliburn',
        'iceandfire:dragonarmor_dragonsteel_fire_head', 'iceandfire:dragonarmor_dragonsteel_fire_neck', 'iceandfire:dragonarmor_dragonsteel_fire_body',
        'iceandfire:dragonarmor_dragonsteel_fire_tail', 'iceandfire:dragonarmor_dragonsteel_ice_head', 'iceandfire:dragonarmor_dragonsteel_ice_neck',
        'iceandfire:dragonarmor_dragonsteel_ice_body', 'iceandfire:dragonarmor_dragonsteel_ice_tail', 'iceandfire:dragonarmor_dragonsteel_lightning_head',
        'iceandfire:dragonarmor_dragonsteel_lightning_neck', 'iceandfire:dragonarmor_dragonsteel_lightning_body', 'iceandfire:dragonarmor_dragonsteel_lightning_tail',
        'iceandfire:hippogryph_sword', 'iceandfire:gorgon_head', 'iceandfire:pixie_wand', 'iceandfire:cyclops_eye', 'iceandfire:siren_flute', 'iceandfire:hippocampus_slapper',
        'iceandfire:cockatrice_scepter', 'iceandfire:stymphalian_feather_bundle', 'iceandfire:stymphalian_bird_dagger', 'iceandfire:myrmex_desert_swarm',
        'iceandfire:myrmex_jungle_swarm', 'iceandfire:deathworm_gauntlet_yellow', 'iceandfire:deathworm_gauntlet_white', 'iceandfire:deathworm_gauntlet_red',
        'iceandfire:amphithere_macuahuitl', 'iceandfire:dragonsteel_fire_sword', 'iceandfire:dragonsteel_fire_pickaxe', 'iceandfire:dragonsteel_fire_axe',
        'iceandfire:dragonsteel_fire_shovel', 'iceandfire:dragonsteel_fire_hoe', 'iceandfire:dragonsteel_fire_ingot', 'iceandfire:dragonsteel_ice_sword',
        'iceandfire:dragonsteel_ice_pickaxe', 'iceandfire:dragonsteel_ice_axe', 'iceandfire:dragonsteel_ice_shovel', 'iceandfire:dragonsteel_ice_hoe',
        'iceandfire:dragonsteel_ice_ingot', 'iceandfire:dragonsteel_lightning_sword', 'iceandfire:dragonsteel_lightning_pickaxe', 'iceandfire:dragonsteel_lightning_axe',
        'iceandfire:dragonsteel_lightning_shovel', 'iceandfire:dragonsteel_lightning_hoe', 'iceandfire:dragonsteel_lightning_ingot', 'iceandfire:weezer_blue_album',
        'iceandfire:dragonsteel_lightning_helmet', 'iceandfire:dragonsteel_lightning_chestplate', 'iceandfire:dragonsteel_lightning_leggings',
        'iceandfire:dragonsteel_lightning_boots', 'iceandfire:dragonsteel_ice_helmet', 'iceandfire:dragonsteel_ice_chestplate', 'iceandfire:dragonsteel_ice_leggings',
        'iceandfire:dragonsteel_ice_boots', 'iceandfire:dragonsteel_fire_helmet', 'iceandfire:dragonsteel_fire_chestplate', 'iceandfire:dragonsteel_fire_leggings',
        'iceandfire:dragonsteel_fire_boots', 'iceandfire:hydra_heart', 'iceandfire:ghost_sword', 'iceandfire:troll_weapon_axe', 'iceandfire:troll_weapon_column',
        'iceandfire:troll_weapon_column_forest', 'iceandfire:troll_weapon_column_frost', 'iceandfire:troll_weapon_hammer', 'iceandfire:troll_weapon_trunk',
        'iceandfire:troll_weapon_trunk_frost', 'ars_elemental:mark_of_mastery', 'ars_elemental:spell_horn', 'ars_nouveau:archmage_spell_book', 'ars_nouveau:creative_spell_book',
        'ars_nouveau:wand', 'ars_nouveau:spell_bow', 'ars_nouveau:enchanters_sword', 'ars_nouveau:enchanters_shield', 'ars_nouveau:summon_focus', 'ars_nouveau:shapers_focus',
        'ars_nouveau:enchanters_mirror', 'ars_nouveau:alchemists_crown', 'ars_nouveau:spell_crossbow', 'ars_nouveau:enchanters_eye', 'ars_nouveau:creative_source_jar',
        'estrogen:dormant_dream_block', 'experienceobelisk:primordial_assembly', 'experienceobelisk:experience_obelisk', 'justhammers:destructor_core', 'cataclysm:mech_eye',
        'cataclysm:flame_eye', 'cataclysm:void_eye', 'cataclysm:monstrous_eye', 'cataclysm:abyss_eye', 'cataclysm:desert_eye', 'cataclysm:cursed_eye',
        'call_of_yucutan:ah_puch_idol', 'call_of_yucutan:kukulkan_idol', 'twilightforest:uncrafting_table', 'twilightforest:naga_trophy', 'twilightforest:lich_trophy',
        'twilightforest:minoshroom_trophy', 'twilightforest:hydra_trophy', 'twilightforest:knight_phantom_trophy', 'twilightforest:ur_ghast_trophy',
        'twilightforest:alpha_yeti_trophy', 'twilightforest:snow_queen_trophy', 'twilightforest:quest_ram_trophy', 'arsdelight:enchanters_knife',
        'alexsmobs:shattered_dimensional_carver', 'architects_palette:unobtanium', 'dreadsteel:dreadsteel_ingot', 'minecraft:trident', 'dreadsteel:dreadsteel_helmet',
        'dreadsteel:dreadsteel_chestplate', 'dreadsteel:dreadsteel_leggings', 'dreadsteel:dreadsteel_boots', 'dreadsteel:dreadsteel_scythe', 'dreadsteel:dreadsteel_shield',
        'architects_palette:unobtanium_block', 'minecraft:end_portal_frame', 'samurai_dynasty:tyr_samurai_helmet', 'samurai_dynasty:tyr_samurai_chestplate', 'samurai_dynasty:tyr_samurai_leggings',
        'samurai_dynasty:tyr_samurai_boots', 'samurai_dynasty:neptunium_samurai_helmet', 'samurai_dynasty:neptunium_samurai_chestplate', 'samurai_dynasty:neptunium_samurai_leggings',
        'samurai_dynasty:neptunium_samurai_boots', 'samurai_dynasty:mage_samurai_helmet', 'samurai_dynasty:mage_samurai_chestplate', 'samurai_dynasty:mage_samurai_leggings',
        'dimdungeons:item_blank_teleporter_key', 'iceandfire:creative_dragon_meal', 'ars_elemental:fire_turret', 'ars_elemental:water_turret', 'ars_elemental:air_turret',
        'ars_elemental:earth_turret', 'ars_elemental:manipulation_turret', 'not_enough_glyphs:spell_binder', 'experienceobelisk:extravagant_agar',
        'experienceobelisk:flask_of_poseidon', 'experienceobelisk:flask_of_hades', 'experienceobelisk:flask_of_chaos', 'estrogen:uwu', 'apotheosis:treasure_shelf',
        'apotheosis:ender_library', 'aether:invisibility_cloak', 'aether:regeneration_stone', 'ancient_aether:strength_stone', 'aether:life_shard', 'ancient_aether:divine_shovel',
        'ancient_aether:divine_pickaxe', 'ancient_aether:divine_axe', 'ancient_aether:divine_hoe', 'aether:pig_slayer', 'aether:vampire_blade',
        'ancient_aether:mysterious_armor_trim_smithing_template', 'ancient_aether:mechanical_armor_trim_smithing_template', 'ancient_aether:mosaic_armor_trim_smithing_template',
        'ancient_aether:royal_armor_trim_smithing_template', 'ancient_aether:solar_armor_trim_smithing_template', 'ancient_aether:ancient_armor_trim_smithing_template',
        'iceandfire:dragonsteel_fire_block', 'iceandfire:dragonsteel_ice_block', 'iceandfire:dragonsteel_lightning_block', 'aether:obsidian_helmet', 'aether:obsidian_chestplate',
        'aether:obsidian_leggings', 'aether:obsidian_boots', 'aether:obsidian_gloves', 'experienceobelisk:fortuitous_amulet', 'experienceobelisk:memory_tablet',
        'cataclysm:storm_eye', 'psi:cad_assembly_creative', 'kubejs:withered_smithing_template', 'traveloptics:eye_of_nothingness'
    ]
    epic_items.forEach(element => epic(element))
    
})