// Remove recipes for items which are crafted in the Hephaestus Forge
ServerEvents.recipes(event => {

    // Advanced Materials
    event.remove({id: 'create:crafting/materials/electron_tube'})
    event.remove({id: 'create:sequenced_assembly/precision_mechanism'})
    event.remove({id: 'create:sequenced_assembly/sturdy_sheet'})
    event.remove([{id: 'ars_elemental:mark_of_mastery'}, {id: 'ars_elemental:imbuement_mark_of_mastery'}])
    // Materials
    event.remove({id: 'experienceobelisk:bibliophage'})
    event.remove({id: 'apotheosis:prismatic_web'})
    // Charms
    event.remove({id: 'ars_elemental:siren_charm'})
    event.remove({id: 'ars_elemental:firenando_charm'})
    event.remove({id: 'ars_nouveau:starbuncle_charm'})
    event.remove({id: 'ars_nouveau:drygmy_charm'})
    event.remove({id: 'ars_nouveau:whirlisprig_charm'})
    event.remove({id: 'ars_nouveau:wixie_charm'})
    event.remove({id: 'tarotcards:tarot_deck'})
    event.remove({id: 'ars_elemental:air_bangle'})
    event.remove({id: 'ars_elemental:anima_bangle'})
    event.remove({id: 'ars_elemental:earth_bangle'})
    event.remove({id: 'ars_elemental:water_bangle'})
    event.remove({id: 'ars_elemental:fire_bangle'})
    event.remove({id: 'ars_elemental:summon_bangle'})
    event.remove({id: 'ars_elemental:base_bangle'})
    event.remove({id: 'ars_nouveau:ring_of_lesser_discount'})
    event.remove({id: 'ars_nouveau:ring_of_greater_discount'})
    event.remove({id: 'ars_nouveau:amulet_of_mana_boost'})
    event.remove({id: 'ars_nouveau:amulet_of_mana_regen'})
    event.remove({id: 'hexcasting:lens'})
    event.remove({id: 'experienceobelisk:enlightened_amulet'})
    event.remove({id: 'ars_nouveau:belt_of_levitation'})
    event.remove({id: 'ars_nouveau:belt_of_unstable_gifts'})
    event.remove({id: 'ars_nouveau:jump_ring'})
    event.remove({id: 'experienceobelisk:fortuitous_amulet'})
    // Bookshelves
    event.remove([{id: 'experienceobelisk:enchanted_bookshelf'}, {id: 'experienceobelisk:archivers_bookshelf'}])
    event.remove({id: 'apotheosis:dormant_deepshelf'})
    event.remove({id: 'apotheosis:endshelf'})
    event.remove([{id: 'apotheosis:rectifier'}, {id: 'apotheosis:rectifier_t2'}, {id: 'apotheosis:rectifier_t3'}])
    event.remove([{id: 'apotheosis:sightshelf'}, {id: 'apotheosis:sightshelf_t2'}])
    event.remove({id: 'apotheosis:filtering_shelf'})
    event.remove({id: 'apotheosis:treasure_shelf'})
    // Enchanter's Tools
    event.remove({id: 'ars_nouveau:enchanters_eye'})
    event.remove({id: 'ars_nouveau:enchanters_mirror'})
    event.remove({id: 'ars_nouveau:enchanters_shield'})
    event.remove({id: 'ars_nouveau:enchanters_sword'})
    event.remove({id: 'ars_nouveau:wand'})
    event.remove({id: 'ars_nouveau:spell_bow'})
    event.remove({id: 'ars_nouveau:spell_crossbow'})
    event.remove({id: 'arsdelight:enchanters_knife'})
    event.remove({id: 'ars_elemental:spell_horn'})
    // Ritual Tablets
    event.remove([{id: 'ars_nouveau:ritual_wilden_summon'}, {id: 'ars_nouveau:wilden_summon_alt'}])
    event.remove({id: 'ars_nouveau:ritual_harvest'})
    event.remove({id: 'ars_nouveau:ritual_conjure_island_desert'})
    event.remove({id: 'ars_nouveau:ritual_overgrowth'})
    event.remove({id: 'ars_nouveau:ritual_fertility'})
    event.remove({id: 'ars_nouveau:ritual_sanctuary'})
    event.remove({id: 'ars_nouveau:ritual_flowering'})
    event.remove({id: 'ars_nouveau:ritual_gravity'})
    event.remove({id: 'ars_nouveau:ritual_scrying'})
    event.remove({id: 'ars_nouveau:ritual_containment'})
    event.remove({id: 'ars_nouveau:ritual_warping'})
    event.remove([{id: 'ars_nouveau:ritual_moonfall'}, {id: 'ars_nouveau:moonfall_2'}])
    event.remove({id: 'ars_nouveau:ritual_forestation'})
    event.remove({id: 'ars_nouveau:ritual_animal_summon'})
    event.remove({id: 'ars_nouveau:ritual_restoration'})
    event.remove({id: 'ars_nouveau:ritual_overgrowth'})
    event.remove({id: 'ars_nouveau:ritual_cloudshaping'})
    event.remove([{id: 'ars_nouveau:ritual_flight'}, {id: 'ars_elemental:flight_alt'}])
    event.remove({id: 'ars_nouveau:ritual_conjure_island_plains'})
    event.remove([{id: 'ars_nouveau:ritual_sunrise'}, {id: 'ars_nouveau:sunrise_2'}])
    event.remove({id: 'ars_nouveau:ritual_overgrowth'})
    event.remove({id: 'ars_nouveau:ritual_disintegration'})
    event.remove({id: 'ars_nouveau:ritual_awakening'})
    event.remove({id: 'ars_nouveau:ritual_binding'})
    event.remove({id: 'ars_nouveau:ritual_burrowing'})
    event.remove({id: 'ars_elemental:tablet_ritual_detection'})
    event.remove([{id: 'ars_nouveau:ritual_challenge'}, {id: 'ars_nouveau:challenge_2'}])
    event.remove({id: 'ars_elemental:tablet_ritual_repulsion'})
    event.remove({id: 'ars_elemental:tablet_ritual_attraction'})
    event.remove({id: 'ars_elemental:tablet_ritual_tesla_coil'})
    event.remove({id: 'ars_elemental:tablet_ritual_squirrels'})
    // Misc
    event.remove({id: 'apotheosis:ender_lead'})
    event.remove({id: 'experienceobelisk:memory_tablet'})
})