
#Options for general mod behavior.
[general]
	#You shouldn't manually change the version number.
	configVersion = 6
	#If set to FALSE the block protection on the dungeon dimension will be disabled, making the options in the next section useless.
	globalBlockProtection = true
	#If set to TRUE then dungeon keys are consumed whenever a player enters a dungeon portal.
	hardcoreMode = false
	#If hardcore mode is enabled then players within this radius will also enter the dungeon when the key is consumed.
	hardcoreMultiplayerRadius = 5
	#If set to TRUE then the permissions on the personal build dimension are ignored.
	disablePersonalDimSecurity = false
	#If set to TRUE then portals leading to the dungeon dimension will never open.
	disableAllDungeons = false
	#If set to TRUE then portals leading to the personal build dimension will never open.
	disablePersonalBuildDimension = false
	#If set to TRUE some cheats are available.
	enableDebugCheats = false
	#How many ticks the portal blocks cooldown for.
	portalCooldownTicks = 40
	#The odds of a Key Enscriber taking damage upon use, like an anvil, turning into a Used Key Enscriber. Range 0-100.
	keyEnscriberDowngradeChanceFull = 0
	#The odds of a Used Key Enscriber taking damage upon use, like an anvil, turning into a Damaged Key Enscriber. Range 0-100.
	keyEnscriberDowngradeChanceUsed = 80
	#The odds of a Damaged Key Enscriber being destroyed upon use, like a damaged anvil. Range 0-100.
	keyEnscriberDowngradeChanceDamaged = 100
	#Can be used to limit log spam. Can be set to 'all', 'warn', or 'error'.
	logLevel = "error"
	#Which dimension's worldborder to consider when activating keys. Using dimdungeons:dungeon_dimension may not work for everyone.
	worldborderToRespect = "dimdungeons:dungeon_dimension"
	#The chance for an enemy in a basic dungeon to be carrying a theme key.
	chanceForThemeKeys = 4
	#The speed at which to build a dungeon. Value corresponds to the number of ticks skipped between chunks, to avoid lag spikes.
	dungeonBuildSpeed = 5

#Options for block behavior in the dungeon dimension.
[blocks]
	#List of blocks which any player should be allowed to break, defying the block protection. (For example, gravestones or death chests.) Default value is empty.
	breakingWhitelist = ["gravestone:gravestone"]
	#List of blocks that players will be unable to interact with. It is strongly recommended to preserve the defaults.
	interactionBlacklist = ["minecraft:dispenser", "minecraft:dropper", "minecraft:hopper", "minecraft:anvil", "minecraft:chipped_anvil", "minecraft:damaged_anvil", "minecraft:furnace", "minecraft:note_block", "minecraft:repeater", "minecraft:comparator", "minecraft:redstone_wire", "minecraft:beacon", "minecraft:enchanting_table", "minecraft:smoker", "minecraft:blast_furnace", "minecraft:respawn_anchor", "minecraft:lodestone", "minecraft:beehive", "minecraft:bee_nest", "minecraft:black_bed", "minecraft:blue_bed", "minecraft:brown_bed", "minecraft:cyan_bed", "minecraft:gray_bed", "minecraft:green_bed", "minecraft:light_blue_bed", "minecraft:light_gray_bed", "minecraft:lime_bed", "minecraft:magenta_bed", "minecraft:orange_bed", "minecraft:pink_bed", "minecraft:purple_bed", "minecraft:red_bed", "minecraft:white_bed", "minecraft:yellow_bed", "minecraft:flower_pot", "quark:chute", "quark:crafter", "create:belt", "create:creative_motor", "create:clockwork_bearing", "create:mechanical_bearing", "create:windmill_bearing", "supplementaries:book_pile", "supplementaries:book_pile_horizontal", "supplementaries:pedestal", "supplementaries:statue", "rubinated_nether:freezer"]
	#List of blocks that should never drop items if broken by any means in the dungeon dimension.
	noDropsBlacklist = ["minecraft:cracked_stone_bricks", "supplementaries:book_pile", "supplementaries:book_pile_horizontal"]

